I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 48, in script
    e "dd"
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 48, in script
    e "dd"
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 2573, in execute
    Say.execute(self)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

macOS-15.0.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
Doki Doki BSSM 1.0
Mon Oct 28 09:37:33 2024
